const SYSTEM_INITIAL_VAULT_DEFAULTS = {
    "Shoes": [
        { "rank": 1, "name": "Air Jordan 1 Retro High OG", "link": "https://nike.com/jordan" },
        { "rank": 2, "name": "Adidas Ultraboost Light", "link": "https://adidas.com/ultraboost" },
        { "rank": 3, "name": "Nike Air Max 90 Essentials", "link": "https://nike.com/airmax" },
        { "rank": 4, "name": "New Balance 990v6 Metallic", "link": "https://newbalance.com" },
        { "rank": 5, "name": "Asics Gel-Kayano 30 Premium", "link": "https://asics.com" },
        { "rank": 6, "name": "Puma Clyde Classic Leather", "link": "https://puma.com" },
        { "rank": 7, "name": "Vans Old Skool Core Black", "link": "https://vans.com" },
        { "rank": 8, "name": "Converse Chuck Taylor All Star", "link": "https://converse.com" },
        { "rank": 9, "name": "Salomon XT-6 Expanse Trail", "link": "https://salomon.com" },
        { "rank": 10, "name": "Reebok Club C 85 Vintage", "link": "https://reebok.com" }
    ],
    "Inspiring Athletes": [
        { "rank": 1, "name": "Muhammad Ali", "link": "https://wikipedia.org/wiki/Muhammad_Ali" },
        { "rank": 2, "name": "Michael Jordan", "link": "https://nba.com" },
        { "rank": 3, "name": "Serena Williams", "link": "https://serenawilliams.com" },
        { "rank": 4, "name": "Lionel Messi", "link": "https://intermiamicf.com" },
        { "rank": 5, "name": "Usain Bolt", "link": "https://usainbolt.com" },
        { "rank": 6, "name": "Simone Biles", "link": "https://simonebiles.com" },
        { "rank": 7, "name": "Kobe Bryant", "link": "https://mambaout.com" },
        { "rank": 8, "name": "Tiger Woods", "link": "https://tigerwoods.com" },
        { "rank": 9, "name": "Tom Brady", "link": "https://nfl.com" },
        { "rank": 10, "name": "Lewis Hamilton", "link": "https://lewishamilton.com" }
    ],
    "Tech Devices": [
        { "rank": 1, "name": "iPhone 17 Pro Max", "link": "https://apple.com/iphone" },
        { "rank": 2, "name": "MacBook Pro M5 Max", "link": "https://apple.com/macbook" },
        { "rank": 3, "name": "Samsung Galaxy S26 Ultra", "link": "https://samsung.com" },
        { "rank": 4, "name": "Sony WH-1000XM6 Headphones", "link": "https://sony.com" },
        { "rank": 5, "name": "iPad Pro OLED 13-inch", "link": "https://apple.com/ipad" },
        { "rank": 6, "name": "ASUS ROG Zephyrus G16", "link": "https://asus.com" },
        { "rank": 7, "name": "Google Pixel 10 Pro XL", "link": "https://google.com" },
        { "rank": 8, "name": "Nintendo Switch 2 Pro", "link": "https://nintendo.com" },
        { "rank": 9, "name": "DJI Mini 5 Pro Cine", "link": "https://dji.com" },
        { "rank": 10, "name": "Steam Deck OLED 1TB", "link": "https://steampowered.com" }
    ],
    "Celebrities": [
        { "rank": 1, "name": "Keanu Reeves", "link": "https://imdb.com" },
        { "rank": 2, "name": "Tom Hanks", "link": "https://imdb.com" },
        { "rank": 3, "name": "Denzel Washington", "link": "https://imdb.com" },
        { "rank": 4, "name": "Pedro Pascal", "link": "https://imdb.com" },
        { "rank": 5, "name": "Margot Robbie", "link": "https://imdb.com" },
        { "rank": 6, "name": "Cillian Murphy", "link": "https://imdb.com" },
        { "rank": 7, "name": "Zendaya", "link": "https://imdb.com" },
        { "rank": 8, "name": "Ryan Reynolds", "link": "https://imdb.com" },
        { "rank": 9, "name": "Robert Downey Jr.", "link": "https://imdb.com" },
        { "rank": 10, "name": "Hugh Jackman", "link": "https://imdb.com" }
    ],
    "Post 2000 Movies": [
        { "rank": 1, "name": "The Dark Knight (2008)", "link": "https://warnerbros.com" },
        { "rank": 2, "name": "Inception (2010)", "link": "https://warnerbros.com" },
        { "rank": 3, "name": "Interstellar (2014)", "link": "https://paramount.com" },
        { "rank": 4, "name": "Mad Max: Fury Road (2015)", "link": "https://warnerbros.com" },
        { "rank": 5, "name": "Spider-Man: Into the Spider-Verse", "link": "https://sonypictures.com" },
        { "rank": 6, "name": "Dune: Part Two (2024)", "link": "https://legendary.com" },
        { "rank": 7, "name": "Everything Everywhere All At Once", "link": "https://a24films.com" },
        { "rank": 8, "name": "Parasite (2019)", "link": "https://cj智能.com" },
        { "rank": 9, "name": "Whiplash (2014)", "link": "https://sonypictures.com" },
        { "rank": 10, "name": "The Lord of the Rings: Return of the King", "link": "https://newline.com" }
    ],
    "90s Rap Songs": [
        { "rank": 1, "name": "Juicy - Notorious B.I.G.", "link": "https://badboyrecords.com" },
        { "rank": 2, "name": "C.R.E.A.M. - Wu-Tang Clan", "link": "https://wutangclan.com" },
        { "rank": 3, "name": "California Love - 2Pac & Dr. Dre", "link": "https://deathrowrecords.com" },
        { "rank": 4, "name": "Nuthin' But A G Thang - Dr. Dre", "link": "https://deathrowrecords.com" },
        { "rank": 5, "name": "Shook Ones Pt. II - Mobb Deep", "link": "https://loudrecords.com" },
        { "rank": 6, "name": "The World Is Yours - Nas", "link": "https://columbiarecords.com" },
        { "rank": 7, "name": "Mind Playing Tricks on Me - Geto Boys", "link": "https://rapalotrecords.com" },
        { "rank": 8, "name": "Dear Mama - 2Pac", "link": "https://deathrowrecords.com" },
        { "rank": 9, "name": "Gin and Juice - Snoop Dogg", "link": "https://deathrowrecords.com" },
        { "rank": 10, "name": "Hypnotize - Notorious B.I.G.", "link": "https://badboyrecords.com" }
    ],
    "Post 2010 Video Games": [
        { "rank": 1, "name": "GTA VI", "link": "https://rockstargames.com" },
        { "rank": 2, "name": "Hades II", "link": "https://supergiantgames.com/hades2" },
        { "rank": 3, "name": "Death Stranding 2", "link": "https://kojimaproductions.jp" },
        { "rank": 4, "name": "Hollow Knight: Silksong", "link": "https://teamcherry.com.au" },
        { "rank": 5, "name": "The Witcher 4", "link": "https://cdprojektred.com" },
        { "rank": 6, "name": "Metroid Prime 4", "link": "https://nintendo.com" },
        { "rank": 7, "name": "Fable", "link": "https://xbox.com/games/fable" },
        { "rank": 8, "name": "Perfect Dark", "link": "https://theinitiative.xbox" },
        { "rank": 9, "name": "Wolverine", "link": "https://insomniac.games" },
        { "rank": 10, "name": "Star Wars: Eclipse", "link": "https://starwarseclipse.com" }
    ],
    "Novels": [
        { "rank": 1, "name": "Dune - Frank Herbert", "link": "https://penguinrandomhouse.com" },
        { "rank": 2, "name": "1984 - George Orwell", "link": "https://penguinrandomhouse.com" },
        { "rank": 3, "name": "The Great Gatsby - F. Scott Fitzgerald", "link": "https://simonandschuster.com" },
        { "rank": 4, "name": "To Kill a Mockingbird - Harper Lee", "link": "https://harpercollins.com" },
        { "rank": 5, "name": "The Fellowship of the Ring - Tolkien", "link": "https://hmhbooks.com" },
        { "rank": 6, "name": "Neuromancer - William Gibson", "link": "https://penguinrandomhouse.com" },
        { "rank": 7, "name": "Snow Crash - Neal Stephenson", "link": "https://penguinrandomhouse.com" },
        { "rank": 8, "name": "Project Hail Mary - Andy Weir", "link": "https://penguinrandomhouse.com" },
        { "rank": 9, "name": "Blood Meridian - Cormac McCarthy", "link": "https://penguinrandomhouse.com" },
        { "rank": 10, "name": "The Count of Monte Cristo - Dumas", "link": "https://penguinrandomhouse.com" }
    ],
    "Restaurants": [
        { "rank": 1, "name": "The French Laundry (Yountville)", "link": "https://thomaskeller.com" },
        { "rank": 2, "name": "Central (Lima)", "link": "https://centralrestaurante.com.pe" },
        { "rank": 3, "name": "Atomix (New York)", "link": "https://atomixnyc.com" },
        { "rank": 4, "name": "Asador Etxebarri (Axe)", "link": "https://asadoretxebarri.com" },
        { "rank": 5, "name": "DiverXO (Madrid)", "link": "https://diverxo.com" },
        { "rank": 6, "name": "Osteria Francescana (Modena)", "link": "https://osteriafrancescana.it" },
        { "rank": 7, "name": "Alchemist (Copenhagen)", "link": "https://alchemist.dk" },
        { "rank": 8, "name": "Gaggan Anand (Bangkok)", "link": "https://gaggananand.com" },
        { "rank": 9, "name": "Pujol (Mexico City)", "link": "https://pujol.com.mx" },
        { "rank": 10, "name": "Eleven Madison Park (New York)", "link": "https://elevenmadisonpark.com" }
    ]
};